#! /usr/bin/env node

console.log('This script populates some test weapons to your database. Specified database as argument - e.g.: populatedb mongodb://your_username:your_password@your_dabase_url');

// Get arguments passed on command line
var userArgs = process.argv.slice(2);
if (!userArgs[0].startsWith('mongodb://')) {
    console.log('ERROR: You need to specify a valid mongodb URL as the first argument');
    return
}

// Get weapon model
var Testing = require("./models/loot/testing");
var Weapon = require('./models/loot/weapon');

// Connect to database
var mongoose = require('mongoose');
var mongoDB = userArgs[0];
mongoose.connect(mongoDB);
mongoose.Promise = global.Promise;
var db = mongoose.connection;
mongoose.connection.on('error', console.error.bind(console, 'MongoDB connection error:'));

// Test adding to DB
// Testing.create({
//     name: "Test",
//     number: -1
//   },
//   function (err, small) {
//     if (err) console.log(err);
//     // saved!
// });


// WEAPONS *********************************************************************

// Create common assault-rifle-burst weapon document in Database
Weapon.create({
    image: "/images/weapons/assault-rifle-burst.png",
    fullName: "assault-rifle-burst-common",
    name: "assault-rifle-burst",
    type: "assault-rifle",
    tier: "common",
    tierValue: 0,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 47.2,
    bodyDamageClose: 27,
    headDamageClose: 67.5,
    bodyDamageMid: 27,
    headDamageMid: 67.5,
    bodyDamageLong: 27,
    headDamageLong: 67.5,
    bodyDamageMax: 27,
    headDamageMax: 67.5,
    impactDamageClose: 40,
    impactDamageMid: 40,
    impactDamageLong: 40,
    impactDamageMax: 40,
    environmentalDamageClose: 30,
    environmentalDamageMid: 30,
    environmentalDamageLong: 30,
    environmentalDamageMax: 30,
    baseSpread: .175,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .75,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 1.925,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 9,
    fireRate: 1.75,
    reloadTime: 2.9,
    magazineSize: 30,
    floorLootChance: .645,
    chestLootChance: .645,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create uncommon assault-rifle-burst weapon document in Database
Weapon.create({
    image: "/images/weapons/assault-rifle-burst.png",
    fullName: "assault-rifle-burst-uncommon",
    name: "assault-rifle-burst",
    type: "assault-rifle",
    tier: "uncommon",
    tierValue: 1,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 50.8,
    bodyDamageClose: 29,
    headDamageClose: 72.5,
    bodyDamageMid: 29,
    headDamageMid: 72.5,
    bodyDamageLong: 29,
    headDamageLong: 72.5,
    bodyDamageMax: 29,
    headDamageMax: 72.5,
    impactDamageClose: 42,
    impactDamageMid: 42,
    impactDamageLong: 42,
    impactDamageMax: 42,
    environmentalDamageClose: 30,
    environmentalDamageMid: 30,
    environmentalDamageLong: 30,
    environmentalDamageMax: 30,
    baseSpread: .175,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .75,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 1.8375,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 9,
    fireRate: 1.75,
    reloadTime: 2.7,
    magazineSize: 30,
    floorLootChance: .258,
    chestLootChance: .258,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create rare assault-rifle-burst weapon document in Database
Weapon.create({
    image: "/images/weapons/assault-rifle-burst.png",
    fullName: "assault-rifle-burst-rare",
    name: "assault-rifle-burst",
    type: "assault-rifle",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 52.5,
    bodyDamageClose: 30,
    headDamageClose: 75.0,
    bodyDamageMid: 30,
    headDamageMid: 75.0,
    bodyDamageLong: 30,
    headDamageLong: 75.0,
    bodyDamageMax: 30,
    headDamageMax: 75.0,
    impactDamageClose: 44,
    impactDamageMid: 44,
    impactDamageLong: 44,
    impactDamageMax: 44,
    environmentalDamageClose: 30,
    environmentalDamageMid: 30,
    environmentalDamageLong: 30,
    environmentalDamageMax: 30,
    baseSpread: .175,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .75,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 1.75,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 9,
    fireRate: 1.75,
    reloadTime: 2.6,
    magazineSize: 30,
    floorLootChance: .097,
    chestLootChance: .097,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create common m4 weapon document in Database
Weapon.create({
    image: "/images/weapons/assault-rifle-m4.png",
    fullName: "assault-rifle-m4-common",
    name: "assault-rifle-m4",
    type: "assault-rifle",
    tier: "common",
    tierValue: 0,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 165,
    bodyDamageClose: 30,
    headDamageClose: 60,
    bodyDamageMid: 30,
    headDamageMid: 60,
    bodyDamageLong: 30,
    headDamageLong: 60,
    bodyDamageMax: 30,
    headDamageMax: 60,
    impactDamageClose: 25,
    impactDamageMid: 25,
    impactDamageLong: 25,
    impactDamageMax: 25,
    environmentalDamageClose: 33,
    environmentalDamageMid: 33,
    environmentalDamageLong: 33,
    environmentalDamageMax: 33,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .6,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.5,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 5.5,
    reloadTime: 2.3,
    magazineSize: 30,
    floorLootChance: .518,
    chestLootChance: .518,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create uncommon m4 weapon document in Database
Weapon.create({
    image: "/images/weapons/assault-rifle-m4.png",
    fullName: "assault-rifle-m4-uncommon",
    name: "assault-rifle-m4",
    type: "assault-rifle",
    tier: "uncommon",
    tierValue: 1,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 170.5,
    bodyDamageClose: 31,
    headDamageClose: 62,
    bodyDamageMid: 31,
    headDamageMid: 62,
    bodyDamageLong: 31,
    headDamageLong: 62,
    bodyDamageMax: 31,
    headDamageMax: 62,
    impactDamageClose: 27,
    impactDamageMid: 27,
    impactDamageLong: 27,
    impactDamageMax: 27,
    environmentalDamageClose: 33,
    environmentalDamageMid: 33,
    environmentalDamageLong: 33,
    environmentalDamageMax: 33,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .6,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.4125,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 5.5,
    reloadTime: 2.2,
    magazineSize: 30,
    floorLootChance: .259,
    chestLootChance: .259,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create rare m4 weapon document in Database
Weapon.create({
    image: "/images/weapons/assault-rifle-m4.png",
    fullName: "assault-rifle-m4-rare",
    name: "assault-rifle-m4",
    type: "assault-rifle",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 181.5,
    bodyDamageClose: 33,
    headDamageClose: 66,
    bodyDamageMid: 33,
    headDamageMid: 66,
    bodyDamageLong: 33,
    headDamageLong: 66,
    bodyDamageMax: 33,
    headDamageMax: 66,
    impactDamageClose: 28,
    impactDamageMid: 28,
    impactDamageLong: 28,
    impactDamageMax: 28,
    environmentalDamageClose: 33,
    environmentalDamageMid: 33,
    environmentalDamageLong: 33,
    environmentalDamageMax: 33,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .6,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.325,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 5.5,
    reloadTime: 2.2,
    magazineSize: 30,
    floorLootChance: .104,
    chestLootChance: .104,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create epic scar document in database
Weapon.create({
    image: "/images/weapons/assault-rifle-scar.png",
    fullName: "assault-rifle-scar-epic",
    name: "assault-rifle-scar",
    type: "assault-rifle",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 192.5,
    bodyDamageClose: 35,
    headDamageClose: 70,
    bodyDamageMid: 35,
    headDamageMid: 70,
    bodyDamageLong: 35,
    headDamageLong: 70,
    bodyDamageMax: 35,
    headDamageMax: 70,
    impactDamageClose: 29,
    impactDamageMid: 29,
    impactDamageLong: 29,
    impactDamageMax: 29,
    environmentalDamageClose: 33,
    environmentalDamageMid: 33,
    environmentalDamageLong: 33,
    environmentalDamageMax: 33,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .6,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.2375,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 5.5,
    reloadTime: 2.1,
    magazineSize: 30,
    floorLootChance: .039,
    chestLootChance: .039,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create legendary scar document in database
Weapon.create({
    image: "/images/weapons/assault-rifle-scar.png",
    fullName: "assault-rifle-scar-legendary",
    name: "assault-rifle-scar",
    type: "assault-rifle",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 198,
    bodyDamageClose: 36,
    headDamageClose: 72,
    bodyDamageMid: 36,
    headDamageMid: 72,
    bodyDamageLong: 36,
    headDamageLong: 72,
    bodyDamageMax: 36,
    headDamageMax: 72,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 33,
    environmentalDamageMid: 33,
    environmentalDamageLong: 33,
    environmentalDamageMax: 33,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .6,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 5.5,
    reloadTime: 2.1,
    magazineSize: 30,
    floorLootChance: .001,
    chestLootChance: .001,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create rare assault-rifle-scoped document in database
Weapon.create({
    image: "/images/weapons/assault-rifle-scoped.png",
    fullName: "assault-rifle-scoped-rare",
    name: "assault-rifle-scoped",
    type: "assault-rifle",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 80.5,
    bodyDamageClose: 23,
    headDamageClose: 46,
    bodyDamageMid: 23,
    headDamageMid: 46,
    bodyDamageLong: 23,
    headDamageLong: 46,
    bodyDamageMax: 23,
    headDamageMax: 46,
    impactDamageClose: 28,
    impactDamageMid: 28,
    impactDamageLong: 28,
    impactDamageMax: 28,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: 0,
    standingSpread: .5,
    crouchingSpread: .75,
    horizontalRecoil: 0.2,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .7,
    interpSpeed: 9,
    interpSpeedRecovery: 8,
    fireRate: 3.5,
    reloadTime: 2.3,
    magazineSize: 20,
    floorLootChance: .052,
    chestLootChance: .052,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create epic assault-rifle-scoped document in database
Weapon.create({
    image: "/images/weapons/assault-rifle-scoped.png",
    fullName: "assault-rifle-scoped-epic",
    name: "assault-rifle-scoped",
    type: "assault-rifle",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 84,
    bodyDamageClose: 24,
    headDamageClose: 48,
    bodyDamageMid: 24,
    headDamageMid: 48,
    bodyDamageLong: 24,
    headDamageLong: 48,
    bodyDamageMax: 24,
    headDamageMax: 48,
    impactDamageClose: 29,
    impactDamageMid: 29,
    impactDamageLong: 29,
    impactDamageMax: 29,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: 0,
    standingSpread: .5,
    crouchingSpread: .75,
    horizontalRecoil: 0.2,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 2.85,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .7,
    interpSpeed: 9,
    interpSpeedRecovery: 8,
    fireRate: 3.5,
    reloadTime: 2.2,
    magazineSize: 20,
    floorLootChance: .019,
    chestLootChance: .019,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a epic minigun document in database
Weapon.create({
    image: "/images/weapons/minigun.png",
    fullName: "minigun-epic",
    name: "minigun",
    type: "minigun",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 192,
    bodyDamageClose: 16,
    headDamageClose: 40,
    bodyDamageMid: 16,
    headDamageMid: 40,
    bodyDamageLong: 16,
    headDamageLong: 40,
    bodyDamageMax: 16,
    headDamageMax: 40,
    impactDamageClose: 29,
    impactDamageMid: 29,
    impactDamageLong: 29,
    impactDamageMax: 29,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.325,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.8,
    magazineSize: 0,
    floorLootChance: .667,
    chestLootChance: .667,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a legendary minigun document in database
Weapon.create({
    image: "/images/weapons/minigun.png",
    fullName: "minigun-legendary",
    name: "minigun",
    type: "minigun",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});












// Create a uncommon pump shotgun document in database
Weapon.create({
    image: "/images/weapons/pump-shotgun.png",
    fullName: "pump-shotgun-uncommon",
    name: "pump-shotgun",
    type: "shotgun",
    tier: "uncommon",
    tierValue: 1,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare pump shotgun document in database
Weapon.create({
    image: "/images/weapons/pump-shotgun.png",
    fullName: "pump-shotgun-rare",
    name: "pump-shotgun",
    type: "shotgun",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a common tactical shotgun document in database
Weapon.create({
    image: "/images/weapons/tactical-shotgun.png",
    fullName: "tactical-shotgun-common",
    name: "tactical-shotgun",
    type: "shotgun",
    tier: "common",
    tierValue: 0,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a uncommon tactical shotgun document in database
Weapon.create({
    image: "/images/weapons/tactical-shotgun.png",
    fullName: "tactical-shotgun-uncommon",
    name: "tactical-shotgun",
    type: "shotgun",
    tier: "uncommon",
    tierValue: 1,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare tactical shotgun document in database
Weapon.create({
    image: "/images/weapons/tactical-shotgun.png",
    fullName: "tactical-shotgun-rare",
    name: "tactical-shotgun",
    type: "shotgun",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a epic heavy shotgun document in database
Weapon.create({
    image: "/images/weapons/heavy-shotgun.png",
    fullName: "heavy-shotgun-epic",
    name: "heavy-shotgun",
    type: "shotgun",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a legendary heavy shotgun document in database
Weapon.create({
    image: "/images/weapons/heavy-shotgun.png",
    fullName: "heavy-shotgun-legendary",
    name: "heavy-shotgun",
    type: "shotgun",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an epic hand-cannon document in database
Weapon.create({
    image: "/images/weapons/hand-cannon.png",
    fullName: "hand-cannon-epic",
    name: "hand-cannon",
    type: "pistol",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an legendary hand-cannon document in database
Weapon.create({
    image: "/images/weapons/hand-cannon.png",
    fullName: "hand-cannon-legendary",
    name: "hand-cannon",
    type: "pistol",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a common pistol document in database
Weapon.create({
    image: "/images/weapons/pistol.png",
    fullName: "pistol-common",
    name: "pistol",
    type: "pistol",
    tier: "common",
    tierValue: 0,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an uncommon pistol document in database
Weapon.create({
    image: "/images/weapons/pistol.png",
    fullName: "pistol-uncommon",
    name: "pistol",
    type: "pistol",
    tier: "uncommon",
    tierValue: 1,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare pistol document in database
Weapon.create({
    image: "/images/weapons/pistol.png",
    fullName: "pistol-rare",
    name: "pistol",
    type: "pistol",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a common revolver document in database
Weapon.create({
    image: "/images/weapons/revolver.png",
    fullName: "revolver-common",
    name: "revolver",
    type: "pistol",
    tier: "common",
    tierValue: 0,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an uncommon revolver document in database
Weapon.create({
    image: "/images/weapons/revolver.png",
    fullName: "revolver-uncommon",
    name: "revolver",
    type: "pistol",
    tier: "uncommon",
    tierValue: 1,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare revolver document in database
Weapon.create({
    image: "/images/weapons/revolver.png",
    fullName: "revolver-rare",
    name: "revolver",
    type: "pistol",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an epic suppressed-pistol document in database
Weapon.create({
    image: "/images/weapons/suppressed-pistol.png",
    fullName: "suppressed-pistol-epic",
    name: "suppressed-pistol",
    type: "pistol",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an legendary suppressed-pistol document in database
Weapon.create({
    image: "/images/weapons/suppressed-pistol.png",
    fullName: "suppressed-pistol-legendary",
    name: "suppressed-pistol",
    type: "pistol",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a common suppressed submachine-gun document in database
Weapon.create({
    image: "/images/weapons/suppressed-submachine-gun.png",
    fullName: "suppressed-submachine-gun-common",
    name: "suppressed-submachine-gun",
    type: "submachine-gun",
    tier: "common",
    tierValue: 0,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an uncommon suppressed submachine-gun document in database
Weapon.create({
    image: "/images/weapons/suppressed-submachine-gun.png",
    fullName: "suppressed-submachine-gun-uncommon",
    name: "suppressed-submachine-gun",
    type: "submachine-gun",
    tier: "uncommon",
    tierValue: 1,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare suppressed submachine-gun document in database
Weapon.create({
    image: "/images/weapons/suppressed-submachine-gun.png",
    fullName: "suppressed-submachine-gun-rare",
    name: "suppressed-submachine-gun",
    type: "submachine-gun",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a uncommon tactical submachine-gun document in database
Weapon.create({
    image: "/images/weapons/tactical-submachine-gun.png",
    fullName: "tactical-submachine-gun-uncommon",
    name: "tactical-submachine-gun",
    type: "submachine-gun",
    tier: "uncommon",
    tierValue: 1,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare tactical submachine-gun document in database
Weapon.create({
    image: "/images/weapons/tactical-submachine-gun.png",
    fullName: "tactical-submachine-gun-rare",
    name: "tactical-submachine-gun",
    type: "submachine-gun",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a epic tactical submachine-gun document in database
Weapon.create({
    image: "/images/weapons/tactical-submachine-gun.png",
    fullName: "tactical-submachine-gun-epic",
    name: "tactical-submachine-gun",
    type: "submachine-gun",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare bolt-action-sniper-rifle document in database
Weapon.create({
    image: "/images/weapons/bolt-action-sniper-rifle.png",
    fullName: "bolt-action-sniper-rifle-rare",
    name: "bolt-action-sniper-rifle",
    type: "sniper-rifle",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a epic bolt-action-sniper-rifle document in database
Weapon.create({
    image: "/images/weapons/bolt-action-sniper-rifle.png",
    fullName: "bolt-action-sniper-rifle-epic",
    name: "bolt-action-sniper-rifle",
    type: "sniper-rifle",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a legendary bolt-action-sniper-rifle document in database
Weapon.create({
    image: "/images/weapons/bolt-action-sniper-rifle.png",
    fullName: "bolt-action-sniper-rifle-legendary",
    name: "bolt-action-sniper-rifle",
    type: "sniper-rifle",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a epic semi-auto-sniper-rifle document in database
Weapon.create({
    image: "/images/weapons/semi-auto-sniper-rifle.png",
    fullName: "semi-auto-sniper-rifle-epic",
    name: "semi-auto-sniper-rifle",
    type: "sniper-rifle",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a legendary semi-auto-sniper-rifle document in database
Weapon.create({
    image: "/images/weapons/semi-auto-sniper-rifle.png",
    fullName: "semi-auto-sniper-rifle-legendary",
    name: "semi-auto-sniper-rifle",
    type: "sniper-rifle",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an uncommon hunting-rifle document in database
Weapon.create({
    image: "/images/weapons/hunting-rifle.png",
    fullName: "hunting-rifle-uncommon",
    name: "hunting-rifle",
    type: "sniper-rifle",
    tier: "uncommon",
    tierValue: 1,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an rare hunting-rifle document in database
Weapon.create({
    image: "/images/weapons/hunting-rifle.png",
    fullName: "hunting-rifle-rare",
    name: "hunting-rifle",
    type: "sniper-rifle",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare crossbow document in database
Weapon.create({
    image: "/images/weapons/crossbow.png",
    fullName: "crossbow-rare",
    name: "crossbow",
    type: "sniper-rifle",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create an epic crossbow document in database
Weapon.create({
    image: "/images/weapons/crossbow.png",
    fullName: "crossbow-epic",
    name: "crossbow",
    type: "sniper-rifle",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare grenade-launcher document in database
Weapon.create({
    image: "/images/weapons/grenade-launcher.png",
    fullName: "grenade-launcher-rare",
    name: "grenade-launcher",
    type: "launcher",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a epic grenade-launcher document in database
Weapon.create({
    image: "/images/weapons/grenade-launcher.png",
    fullName: "grenade-launcher-epic",
    name: "grenade-launcher",
    type: "launcher",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a legendary grenade-launcher document in database
Weapon.create({
    image: "/images/weapons/grenade-launcher.png",
    fullName: "grenade-launcher-legendary",
    name: "grenade-launcher",
    type: "launcher",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a epic guided-missile document in database
Weapon.create({
    image: "/images/weapons/guided-missile.png",
    fullName: "guided-missile-epic",
    name: "guided-missile",
    type: "launcher",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a legendary guided-missile document in database
Weapon.create({
    image: "/images/weapons/guided-missile.png",
    fullName: "guided-missile-legendary",
    name: "guided-missile",
    type: "launcher",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare rocket-launcher document in database
Weapon.create({
    image: "/images/weapons/rocket-launcher.png",
    fullName: "rocket-launcher-rare",
    name: "rocket-launcher",
    type: "launcher",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a epic rocket-launcher document in database
Weapon.create({
    image: "/images/weapons/rocket-launcher.png",
    fullName: "rocket-launcher-epic",
    name: "rocket-launcher",
    type: "launcher",
    tier: "epic",
    tierValue: 3,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a legendary rocket-launcher document in database
Weapon.create({
    image: "/images/weapons/rocket-launcher.png",
    fullName: "rocket-launcher-legendary",
    name: "rocket-launcher",
    type: "launcher",
    tier: "legendary",
    tierValue: 4,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a common grenade document in database
Weapon.create({
    image: "/images/weapons/grenade.png",
    fullName: "grenade-common",
    name: "grenade",
    type: "grenade",
    tier: "common",
    tierValue: 0,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare boogie-bomb document in database
Weapon.create({
    image: "/images/weapons/boogie-bomb.png",
    fullName: "boogie-bomb-rare",
    name: "boogie-bomb",
    type: "grenade",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});

// Create a rare impulse-grenade document in database
Weapon.create({
    image: "/images/weapons/impulse-grenade.png",
    fullName: "impulse-grenade-rare",
    name: "impulse-grenade",
    type: "grenade",
    tier: "rare",
    tierValue: 2,
    closeRange: 1,
    midrange: 1,
    longRange: 1,
    maxRange: 25000,
    damagePerSecond: 204,
    bodyDamageClose: 17,
    headDamageClose: 42.5,
    bodyDamageMid: 17,
    headDamageMid: 42.5,
    bodyDamageLong: 17,
    headDamageLong: 42.5,
    bodyDamageMax: 17,
    headDamageMax: 42.5,
    impactDamageClose: 31,
    impactDamageMid: 31,
    impactDamageLong: 31,
    impactDamageMax: 31,
    environmentalDamageClose: 25,
    environmentalDamageMid: 25,
    environmentalDamageLong: 25,
    environmentalDamageMax: 25,
    baseSpread: .15,
    sprintSpread: 1.5,
    fallingJumpingSpread: 1.25,
    adsSpread: .65,
    standingSpread: .55,
    crouchingSpread: .8,
    horizontalRecoil: 0.25,
    horizontalRecoilGamepad: 1,
    verticalRecoil: 3.15,
    verticalRecoilGamepad: .5,
    angleMax: 25,
    angleMin: -25,
    adsRecoil: .5,
    interpSpeed: 12,
    interpSpeedRecovery: 6,
    fireRate: 12,
    reloadTime: 4.5,
    magazineSize: 0,
    floorLootChance: .333,
    chestLootChance: .333,
    supplyDropLootChance: 0
  },
  function (err, small) {
    if (err) console.log(err);
    // saved!
});



